name: akka-stream

on:
  push:
    branches:
      - master
    paths:
      - 'akka-stream/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: ./gradlew --stacktrace -Dbintray_username=${{ secrets.BINTRAY_USERNAME }} -Dbintray_apikey=${{ secrets.BINTRAY_APIKEY }} -Dgithub_token=${{ secrets.GITHUB_TOKEN }} clean build publish
